bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 10263dedfb7b3b1cd59bf81e49bb260e9e3e85c6

configMapGenerator:
- name: mykustom-map
  env: config.properties