bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 4236bb69be058c7db076f9f3391a6f7472af3a14

configMapGenerator:
- name: mykustom-map
  env: config.properties