bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 69cc1af2a6d60f2bf2498dd506800e24c6826cd6

configMapGenerator:
- name: mykustom-map
  env: config.properties