bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: d88a698f36b92f8cc8568a5e8ab4071298119494

configMapGenerator:
- name: mykustom-map
  env: config.properties