bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: e6ad705134c523f2ca4c90fe08f1d29a4d3eba24

configMapGenerator:
- name: mykustom-map
  env: config.properties