bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 108947a013ac4f627c60bea9eb6100decb0a26df

configMapGenerator:
- name: mykustom-map
  env: config.properties