bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 0d43f099577d78df3b753eced9cdc976309454f1

configMapGenerator:
- name: mykustom-map
  env: config.properties