bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 63a638592c555dcb65bb13b03ecb1a17a03ee1d1

configMapGenerator:
- name: mykustom-map
  env: config.properties