bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 547947cca2ee13753b8c5979f6bad5f7dc1a3e6b

configMapGenerator:
- name: mykustom-map
  env: config.properties