bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: aed189d478041c1510d29dd12754977b06315e5b

configMapGenerator:
- name: mykustom-map
  env: config.properties