bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: eaaf2679d04615f4d221873137b4a0fd175d335c

configMapGenerator:
- name: mykustom-map
  env: config.properties