bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 937914166f4559ec433a42efd4b4781c90b6d33b

configMapGenerator:
- name: mykustom-map
  env: config.properties