bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 9d9f81605e148e0b97ee88efeecb2b12f743c228

configMapGenerator:
- name: mykustom-map
  env: config.properties