bases:
- ../../base

patches:
- path: replicas.yaml

images:
- name: kevmeans/python-microservice-test
  newTag: 72fb4265f9ec8dbfe6e65c1ce6468dec6070fd97

configMapGenerator:
- name: mykustom-map
  env: config.properties