apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 8088
    targetPort: 80
    name: http-port