project: default
source:
  repoURL: 'https://github.com/kevinmeans/k8-manifest'
  path: overlays/dev
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dev
syncPolicy:
  automated:
    prune: true
  syncOptions:
    - CreateNamespace=true