apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: python-microservice-test-preview-app
spec:
  generators:
    - pullRequest:
        github:
          owner: kevinmeans
          repo: python-microservice-test
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'python-microservice-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        
        path: preview/
        repoURL: 'https://github.com/kevinmeans/k8-manifest.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{branch}}'
            - name: version
              value: '{{head_sha}}'
            - name: image
              value: kevmeans/python-microservice-test
            - name: name
              value: python-microservice-preview
      
      syncPolicy:
        automated:
          selfHeal: true