apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: python-microservice-preview-app
spec:
  generators:
    - pullRequest:
        github:
          owner: kevinmeans
          repo: python-microservice
          tokenRef:
            key: token
            secretName: github-token
        requeueAfterSeconds: 60
  template:
    metadata:
      # Cant use {{branch}} because lowercase values only.
      name: 'python-microservice-preview-{{number}}'
    spec:
      destination:
        namespace: 'preview'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: preview/
        repoURL: 'https://github.com/kevinmeans/k8-manifest.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview'
            - name: version
              value: '{{branch}}-{{head_sha}}'
            - name: image
              value: kevmeans/python-microservice
            - name: name
              value: python-microservice-preview
      
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true