apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
      - name: fast-api-container
        image: "kevmeans/python-microservice-test:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mykustom-map
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"